/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAiSettingsRouteImport } from './routes/_authenticated/ai-settings'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedGroupsRouteImport } from './routes/_authenticated/groups'
import { Route as AuthenticatedJobsRouteImport } from './routes/_authenticated/jobs'
import { Route as AuthenticatedLogsRouteImport } from './routes/_authenticated/logs'
import { Route as AuthenticatedMessagesRouteImport } from './routes/_authenticated/messages'
import { Route as AuthenticatedTemplatesRouteImport } from './routes/_authenticated/templates'
import { Route as AuthenticatedWarmupRouteImport } from './routes/_authenticated/warmup'
import { Route as AuthenticatedWorkerHealthRouteImport } from './routes/_authenticated/worker-health'
import { Route as AuthenticatedWorkersRouteImport } from './routes/_authenticated/workers'
import { Route as AuthenticatedBotsIndexRouteImport } from './routes/_authenticated/bots.index'
import { Route as AuthenticatedBotsBotIdRouteImport } from './routes/_authenticated/bots.$botId'
import { Route as AuthenticatedRecipientsIndexRouteImport } from './routes/_authenticated/recipients.index'
import { Route as AuthenticatedRecipientsRecipientIdRouteImport } from './routes/_authenticated/recipients.$recipientId'
import { Route as ApiPublicCronMaintenanceRouteImport } from './routes/api/public/cron/maintenance'
import { Route as ApiPublicCronPlanRouteImport } from './routes/api/public/cron/plan'
import { Route as ApiPublicWorkerEventsRouteImport } from './routes/api/public/worker/events'
import { Route as ApiPublicWorkerHeartbeatRouteImport } from './routes/api/public/worker/heartbeat'
import { Route as ApiPublicWorkerIpReportRouteImport } from './routes/api/public/worker/ip-report'
import { Route as ApiPublicWorkerMessagesRouteImport } from './routes/api/public/worker/messages'
import { Route as ApiPublicWorkerPollRouteImport } from './routes/api/public/worker/poll'
import { Route as ApiPublicWorkerRecipientsRouteImport } from './routes/api/public/worker/recipients'
import { Route as ApiPublicWorkerResultRouteImport } from './routes/api/public/worker/result'
import { Route as ApiPublicWorkerSessionRouteImport } from './routes/api/public/worker/session'
import { Route as ApiPublicWorkerUnlockRouteImport } from './routes/api/public/worker/unlock'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAiSettingsRoute = AuthenticatedAiSettingsRouteImport.update({
  id: '/ai-settings',
  path: '/ai-settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGroupsRoute = AuthenticatedGroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedJobsRoute = AuthenticatedJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLogsRoute = AuthenticatedLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMessagesRoute = AuthenticatedMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTemplatesRoute = AuthenticatedTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWarmupRoute = AuthenticatedWarmupRouteImport.update({
  id: '/warmup',
  path: '/warmup',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWorkerHealthRoute =
  AuthenticatedWorkerHealthRouteImport.update({
    id: '/worker-health',
    path: '/worker-health',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWorkersRoute = AuthenticatedWorkersRouteImport.update({
  id: '/workers',
  path: '/workers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBotsIndexRoute = AuthenticatedBotsIndexRouteImport.update({
  id: '/bots/',
  path: '/bots/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBotsBotIdRoute = AuthenticatedBotsBotIdRouteImport.update({
  id: '/bots/$botId',
  path: '/bots/$botId',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRecipientsIndexRoute =
  AuthenticatedRecipientsIndexRouteImport.update({
    id: '/recipients/',
    path: '/recipients/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRecipientsRecipientIdRoute =
  AuthenticatedRecipientsRecipientIdRouteImport.update({
    id: '/recipients/$recipientId',
    path: '/recipients/$recipientId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicCronMaintenanceRoute =
  ApiPublicCronMaintenanceRouteImport.update({
    id: '/api/public/cron/maintenance',
    path: '/api/public/cron/maintenance',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronPlanRoute = ApiPublicCronPlanRouteImport.update({
  id: '/api/public/cron/plan',
  path: '/api/public/cron/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWorkerEventsRoute = ApiPublicWorkerEventsRouteImport.update({
  id: '/api/public/worker/events',
  path: '/api/public/worker/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWorkerHeartbeatRoute =
  ApiPublicWorkerHeartbeatRouteImport.update({
    id: '/api/public/worker/heartbeat',
    path: '/api/public/worker/heartbeat',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWorkerIpReportRoute = ApiPublicWorkerIpReportRouteImport.update({
  id: '/api/public/worker/ip-report',
  path: '/api/public/worker/ip-report',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWorkerMessagesRoute = ApiPublicWorkerMessagesRouteImport.update({
  id: '/api/public/worker/messages',
  path: '/api/public/worker/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWorkerPollRoute = ApiPublicWorkerPollRouteImport.update({
  id: '/api/public/worker/poll',
  path: '/api/public/worker/poll',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWorkerRecipientsRoute =
  ApiPublicWorkerRecipientsRouteImport.update({
    id: '/api/public/worker/recipients',
    path: '/api/public/worker/recipients',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWorkerResultRoute = ApiPublicWorkerResultRouteImport.update({
  id: '/api/public/worker/result',
  path: '/api/public/worker/result',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWorkerSessionRoute = ApiPublicWorkerSessionRouteImport.update({
  id: '/api/public/worker/session',
  path: '/api/public/worker/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWorkerUnlockRoute = ApiPublicWorkerUnlockRouteImport.update({
  id: '/api/public/worker/unlock',
  path: '/api/public/worker/unlock',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/ai-settings': typeof AuthenticatedAiSettingsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/groups': typeof AuthenticatedGroupsRoute
  '/jobs': typeof AuthenticatedJobsRoute
  '/logs': typeof AuthenticatedLogsRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/templates': typeof AuthenticatedTemplatesRoute
  '/warmup': typeof AuthenticatedWarmupRoute
  '/worker-health': typeof AuthenticatedWorkerHealthRoute
  '/workers': typeof AuthenticatedWorkersRoute
  '/bots/$botId': typeof AuthenticatedBotsBotIdRoute
  '/recipients/$recipientId': typeof AuthenticatedRecipientsRecipientIdRoute
  '/bots/': typeof AuthenticatedBotsIndexRoute
  '/recipients/': typeof AuthenticatedRecipientsIndexRoute
  '/api/public/cron/maintenance': typeof ApiPublicCronMaintenanceRoute
  '/api/public/cron/plan': typeof ApiPublicCronPlanRoute
  '/api/public/worker/events': typeof ApiPublicWorkerEventsRoute
  '/api/public/worker/heartbeat': typeof ApiPublicWorkerHeartbeatRoute
  '/api/public/worker/ip-report': typeof ApiPublicWorkerIpReportRoute
  '/api/public/worker/messages': typeof ApiPublicWorkerMessagesRoute
  '/api/public/worker/poll': typeof ApiPublicWorkerPollRoute
  '/api/public/worker/recipients': typeof ApiPublicWorkerRecipientsRoute
  '/api/public/worker/result': typeof ApiPublicWorkerResultRoute
  '/api/public/worker/session': typeof ApiPublicWorkerSessionRoute
  '/api/public/worker/unlock': typeof ApiPublicWorkerUnlockRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/ai-settings': typeof AuthenticatedAiSettingsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/groups': typeof AuthenticatedGroupsRoute
  '/jobs': typeof AuthenticatedJobsRoute
  '/logs': typeof AuthenticatedLogsRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/templates': typeof AuthenticatedTemplatesRoute
  '/warmup': typeof AuthenticatedWarmupRoute
  '/worker-health': typeof AuthenticatedWorkerHealthRoute
  '/workers': typeof AuthenticatedWorkersRoute
  '/bots/$botId': typeof AuthenticatedBotsBotIdRoute
  '/recipients/$recipientId': typeof AuthenticatedRecipientsRecipientIdRoute
  '/bots': typeof AuthenticatedBotsIndexRoute
  '/recipients': typeof AuthenticatedRecipientsIndexRoute
  '/api/public/cron/maintenance': typeof ApiPublicCronMaintenanceRoute
  '/api/public/cron/plan': typeof ApiPublicCronPlanRoute
  '/api/public/worker/events': typeof ApiPublicWorkerEventsRoute
  '/api/public/worker/heartbeat': typeof ApiPublicWorkerHeartbeatRoute
  '/api/public/worker/ip-report': typeof ApiPublicWorkerIpReportRoute
  '/api/public/worker/messages': typeof ApiPublicWorkerMessagesRoute
  '/api/public/worker/poll': typeof ApiPublicWorkerPollRoute
  '/api/public/worker/recipients': typeof ApiPublicWorkerRecipientsRoute
  '/api/public/worker/result': typeof ApiPublicWorkerResultRoute
  '/api/public/worker/session': typeof ApiPublicWorkerSessionRoute
  '/api/public/worker/unlock': typeof ApiPublicWorkerUnlockRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/ai-settings': typeof AuthenticatedAiSettingsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/groups': typeof AuthenticatedGroupsRoute
  '/_authenticated/jobs': typeof AuthenticatedJobsRoute
  '/_authenticated/logs': typeof AuthenticatedLogsRoute
  '/_authenticated/messages': typeof AuthenticatedMessagesRoute
  '/_authenticated/templates': typeof AuthenticatedTemplatesRoute
  '/_authenticated/warmup': typeof AuthenticatedWarmupRoute
  '/_authenticated/worker-health': typeof AuthenticatedWorkerHealthRoute
  '/_authenticated/workers': typeof AuthenticatedWorkersRoute
  '/_authenticated/bots/$botId': typeof AuthenticatedBotsBotIdRoute
  '/_authenticated/recipients/$recipientId': typeof AuthenticatedRecipientsRecipientIdRoute
  '/_authenticated/bots/': typeof AuthenticatedBotsIndexRoute
  '/_authenticated/recipients/': typeof AuthenticatedRecipientsIndexRoute
  '/api/public/cron/maintenance': typeof ApiPublicCronMaintenanceRoute
  '/api/public/cron/plan': typeof ApiPublicCronPlanRoute
  '/api/public/worker/events': typeof ApiPublicWorkerEventsRoute
  '/api/public/worker/heartbeat': typeof ApiPublicWorkerHeartbeatRoute
  '/api/public/worker/ip-report': typeof ApiPublicWorkerIpReportRoute
  '/api/public/worker/messages': typeof ApiPublicWorkerMessagesRoute
  '/api/public/worker/poll': typeof ApiPublicWorkerPollRoute
  '/api/public/worker/recipients': typeof ApiPublicWorkerRecipientsRoute
  '/api/public/worker/result': typeof ApiPublicWorkerResultRoute
  '/api/public/worker/session': typeof ApiPublicWorkerSessionRoute
  '/api/public/worker/unlock': typeof ApiPublicWorkerUnlockRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/ai-settings'
    | '/dashboard'
    | '/groups'
    | '/jobs'
    | '/logs'
    | '/messages'
    | '/templates'
    | '/warmup'
    | '/worker-health'
    | '/workers'
    | '/bots/$botId'
    | '/recipients/$recipientId'
    | '/bots/'
    | '/recipients/'
    | '/api/public/cron/maintenance'
    | '/api/public/cron/plan'
    | '/api/public/worker/events'
    | '/api/public/worker/heartbeat'
    | '/api/public/worker/ip-report'
    | '/api/public/worker/messages'
    | '/api/public/worker/poll'
    | '/api/public/worker/recipients'
    | '/api/public/worker/result'
    | '/api/public/worker/session'
    | '/api/public/worker/unlock'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/ai-settings'
    | '/dashboard'
    | '/groups'
    | '/jobs'
    | '/logs'
    | '/messages'
    | '/templates'
    | '/warmup'
    | '/worker-health'
    | '/workers'
    | '/bots/$botId'
    | '/recipients/$recipientId'
    | '/bots'
    | '/recipients'
    | '/api/public/cron/maintenance'
    | '/api/public/cron/plan'
    | '/api/public/worker/events'
    | '/api/public/worker/heartbeat'
    | '/api/public/worker/ip-report'
    | '/api/public/worker/messages'
    | '/api/public/worker/poll'
    | '/api/public/worker/recipients'
    | '/api/public/worker/result'
    | '/api/public/worker/session'
    | '/api/public/worker/unlock'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/ai-settings'
    | '/_authenticated/dashboard'
    | '/_authenticated/groups'
    | '/_authenticated/jobs'
    | '/_authenticated/logs'
    | '/_authenticated/messages'
    | '/_authenticated/templates'
    | '/_authenticated/warmup'
    | '/_authenticated/worker-health'
    | '/_authenticated/workers'
    | '/_authenticated/bots/$botId'
    | '/_authenticated/recipients/$recipientId'
    | '/_authenticated/bots/'
    | '/_authenticated/recipients/'
    | '/api/public/cron/maintenance'
    | '/api/public/cron/plan'
    | '/api/public/worker/events'
    | '/api/public/worker/heartbeat'
    | '/api/public/worker/ip-report'
    | '/api/public/worker/messages'
    | '/api/public/worker/poll'
    | '/api/public/worker/recipients'
    | '/api/public/worker/result'
    | '/api/public/worker/session'
    | '/api/public/worker/unlock'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicCronMaintenanceRoute: typeof ApiPublicCronMaintenanceRoute
  ApiPublicCronPlanRoute: typeof ApiPublicCronPlanRoute
  ApiPublicWorkerEventsRoute: typeof ApiPublicWorkerEventsRoute
  ApiPublicWorkerHeartbeatRoute: typeof ApiPublicWorkerHeartbeatRoute
  ApiPublicWorkerIpReportRoute: typeof ApiPublicWorkerIpReportRoute
  ApiPublicWorkerMessagesRoute: typeof ApiPublicWorkerMessagesRoute
  ApiPublicWorkerPollRoute: typeof ApiPublicWorkerPollRoute
  ApiPublicWorkerRecipientsRoute: typeof ApiPublicWorkerRecipientsRoute
  ApiPublicWorkerResultRoute: typeof ApiPublicWorkerResultRoute
  ApiPublicWorkerSessionRoute: typeof ApiPublicWorkerSessionRoute
  ApiPublicWorkerUnlockRoute: typeof ApiPublicWorkerUnlockRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/ai-settings': {
      id: '/_authenticated/ai-settings'
      path: '/ai-settings'
      fullPath: '/ai-settings'
      preLoaderRoute: typeof AuthenticatedAiSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/groups': {
      id: '/_authenticated/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof AuthenticatedGroupsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/jobs': {
      id: '/_authenticated/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof AuthenticatedJobsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/logs': {
      id: '/_authenticated/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof AuthenticatedLogsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/messages': {
      id: '/_authenticated/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AuthenticatedMessagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/templates': {
      id: '/_authenticated/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof AuthenticatedTemplatesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/warmup': {
      id: '/_authenticated/warmup'
      path: '/warmup'
      fullPath: '/warmup'
      preLoaderRoute: typeof AuthenticatedWarmupRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/worker-health': {
      id: '/_authenticated/worker-health'
      path: '/worker-health'
      fullPath: '/worker-health'
      preLoaderRoute: typeof AuthenticatedWorkerHealthRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/workers': {
      id: '/_authenticated/workers'
      path: '/workers'
      fullPath: '/workers'
      preLoaderRoute: typeof AuthenticatedWorkersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bots/': {
      id: '/_authenticated/bots/'
      path: '/bots'
      fullPath: '/bots/'
      preLoaderRoute: typeof AuthenticatedBotsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bots/$botId': {
      id: '/_authenticated/bots/$botId'
      path: '/bots/$botId'
      fullPath: '/bots/$botId'
      preLoaderRoute: typeof AuthenticatedBotsBotIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recipients/': {
      id: '/_authenticated/recipients/'
      path: '/recipients'
      fullPath: '/recipients/'
      preLoaderRoute: typeof AuthenticatedRecipientsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recipients/$recipientId': {
      id: '/_authenticated/recipients/$recipientId'
      path: '/recipients/$recipientId'
      fullPath: '/recipients/$recipientId'
      preLoaderRoute: typeof AuthenticatedRecipientsRecipientIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/cron/maintenance': {
      id: '/api/public/cron/maintenance'
      path: '/api/public/cron/maintenance'
      fullPath: '/api/public/cron/maintenance'
      preLoaderRoute: typeof ApiPublicCronMaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/plan': {
      id: '/api/public/cron/plan'
      path: '/api/public/cron/plan'
      fullPath: '/api/public/cron/plan'
      preLoaderRoute: typeof ApiPublicCronPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/worker/events': {
      id: '/api/public/worker/events'
      path: '/api/public/worker/events'
      fullPath: '/api/public/worker/events'
      preLoaderRoute: typeof ApiPublicWorkerEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/worker/heartbeat': {
      id: '/api/public/worker/heartbeat'
      path: '/api/public/worker/heartbeat'
      fullPath: '/api/public/worker/heartbeat'
      preLoaderRoute: typeof ApiPublicWorkerHeartbeatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/worker/ip-report': {
      id: '/api/public/worker/ip-report'
      path: '/api/public/worker/ip-report'
      fullPath: '/api/public/worker/ip-report'
      preLoaderRoute: typeof ApiPublicWorkerIpReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/worker/messages': {
      id: '/api/public/worker/messages'
      path: '/api/public/worker/messages'
      fullPath: '/api/public/worker/messages'
      preLoaderRoute: typeof ApiPublicWorkerMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/worker/poll': {
      id: '/api/public/worker/poll'
      path: '/api/public/worker/poll'
      fullPath: '/api/public/worker/poll'
      preLoaderRoute: typeof ApiPublicWorkerPollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/worker/recipients': {
      id: '/api/public/worker/recipients'
      path: '/api/public/worker/recipients'
      fullPath: '/api/public/worker/recipients'
      preLoaderRoute: typeof ApiPublicWorkerRecipientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/worker/result': {
      id: '/api/public/worker/result'
      path: '/api/public/worker/result'
      fullPath: '/api/public/worker/result'
      preLoaderRoute: typeof ApiPublicWorkerResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/worker/session': {
      id: '/api/public/worker/session'
      path: '/api/public/worker/session'
      fullPath: '/api/public/worker/session'
      preLoaderRoute: typeof ApiPublicWorkerSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/worker/unlock': {
      id: '/api/public/worker/unlock'
      path: '/api/public/worker/unlock'
      fullPath: '/api/public/worker/unlock'
      preLoaderRoute: typeof ApiPublicWorkerUnlockRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAiSettingsRoute: typeof AuthenticatedAiSettingsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedGroupsRoute: typeof AuthenticatedGroupsRoute
  AuthenticatedJobsRoute: typeof AuthenticatedJobsRoute
  AuthenticatedLogsRoute: typeof AuthenticatedLogsRoute
  AuthenticatedMessagesRoute: typeof AuthenticatedMessagesRoute
  AuthenticatedTemplatesRoute: typeof AuthenticatedTemplatesRoute
  AuthenticatedWarmupRoute: typeof AuthenticatedWarmupRoute
  AuthenticatedWorkerHealthRoute: typeof AuthenticatedWorkerHealthRoute
  AuthenticatedWorkersRoute: typeof AuthenticatedWorkersRoute
  AuthenticatedBotsBotIdRoute: typeof AuthenticatedBotsBotIdRoute
  AuthenticatedRecipientsRecipientIdRoute: typeof AuthenticatedRecipientsRecipientIdRoute
  AuthenticatedBotsIndexRoute: typeof AuthenticatedBotsIndexRoute
  AuthenticatedRecipientsIndexRoute: typeof AuthenticatedRecipientsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAiSettingsRoute: AuthenticatedAiSettingsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedGroupsRoute: AuthenticatedGroupsRoute,
  AuthenticatedJobsRoute: AuthenticatedJobsRoute,
  AuthenticatedLogsRoute: AuthenticatedLogsRoute,
  AuthenticatedMessagesRoute: AuthenticatedMessagesRoute,
  AuthenticatedTemplatesRoute: AuthenticatedTemplatesRoute,
  AuthenticatedWarmupRoute: AuthenticatedWarmupRoute,
  AuthenticatedWorkerHealthRoute: AuthenticatedWorkerHealthRoute,
  AuthenticatedWorkersRoute: AuthenticatedWorkersRoute,
  AuthenticatedBotsBotIdRoute: AuthenticatedBotsBotIdRoute,
  AuthenticatedRecipientsRecipientIdRoute:
    AuthenticatedRecipientsRecipientIdRoute,
  AuthenticatedBotsIndexRoute: AuthenticatedBotsIndexRoute,
  AuthenticatedRecipientsIndexRoute: AuthenticatedRecipientsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicCronMaintenanceRoute: ApiPublicCronMaintenanceRoute,
  ApiPublicCronPlanRoute: ApiPublicCronPlanRoute,
  ApiPublicWorkerEventsRoute: ApiPublicWorkerEventsRoute,
  ApiPublicWorkerHeartbeatRoute: ApiPublicWorkerHeartbeatRoute,
  ApiPublicWorkerIpReportRoute: ApiPublicWorkerIpReportRoute,
  ApiPublicWorkerMessagesRoute: ApiPublicWorkerMessagesRoute,
  ApiPublicWorkerPollRoute: ApiPublicWorkerPollRoute,
  ApiPublicWorkerRecipientsRoute: ApiPublicWorkerRecipientsRoute,
  ApiPublicWorkerResultRoute: ApiPublicWorkerResultRoute,
  ApiPublicWorkerSessionRoute: ApiPublicWorkerSessionRoute,
  ApiPublicWorkerUnlockRoute: ApiPublicWorkerUnlockRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
